apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeSelector:
    kubernetes.io/os: windows  
  containers:
  - image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    name: coreimage
    ports:  
      - containerPort: 80
    volumeMounts:
    - mountPath: 'C:\mount\'
      name: azure-file-volume
  volumes:
  - name: azure-file-volume
    persistentVolumeClaim:
      claimName: azurefile-pvc